-- TEMA 1 --

-- Enunciado 1 

CREATE OR REPLACE TYPE T_ASISTENCIA IS OBJECT(
	DIA DATE, 
	FERIADO VARCHAR2(1), -- S o N
	MULTA_AUSENCIAS	NUMBER(8),
	HORAS_EXTRAS	NUMBER(8),
	MEMBER PROCEDURE P_ASIGNAR_FERIADO,
	MEMBER FUNCTION F_ES_FERIADO RETURN BOOLEAN
);

CREATE OR REPLACE TYPE BODY T_ASISTENCIA IS

	-- Verifica si el día es feriado
	MEMBER PROCEDURE P_ASIGNAR_FERIADO IS
		V_DAY VARCHAR2(30);
		V_DATE 	:=  SELF.DIA;
	BEGIN
		-- Verifica la fecha en la tabla de feriado
		SELECT FECHA INTO V_DATE 
		FROM FERIADO  
		WHERE TRUNC(FECHA) = TRUNC(SELF.DIA);

		IF V_DATE IS NULL THEN 
			V_DAY := EXTRACT(DAY FROM V_DATE);

			IF V_DAY IN ('SABADO','DOMINGO') THEN 
				SELF.FERIADO = 'S'
			ELSE
				SELF.FERIADO = 'N'
			END IF;
		ELSE
			SELF.FERIADO = 'N';
		END IF;

	END;


	-- Si es feriado retorna true, caso contrario false
	MEMBER FUNCTION F_ES_FERIADO RETURN BOOLEAN IS 
	BEGIN 
		IF SELF.FERIADO = 'S' THEN 
			RETURN TRUE;
		ELSE 
			RETURN FALSE;
	END;


-- Enunciado 2 --
CREATE TYPE TAB_ASISTENCIA IS VARRAY(31) OF T_ASISTENCIA;


-- Enunciado 3 --
ALTER TABLE PLANILLA ADD ASISTENCIA TAB_ASISTENCIA;
