/*
	Ejercicio 8

	Cree el ciclo LEER-TABLA que puede o no recibir como parámetro el nombre de un proveedor. Deberá leer e imprimir los datos correspondientes a partir de la tabla PROVEEDORES2.
*/

CRAETE OR REPLACE PROCEDURE LEER_TABLA(NOMBRE_PARAM VARCHAR2 DEFAULT NULL)
IS
BEGIN 
	
	IF NOMBRE_PARAM IS NULL THEN
		FOR REG_PROV IN ( SELECT 
							P.ID_PROVEEDOR,
							P.NOMBRE_PROVEEDOR,
							A.ID_ARTICULO,
							A.NOMBRE_ARTICULO
						FROM PROVEEDORES2 P, 
						TABLE(V.ARTICULOS_PROVEIDOS) A) LOOP
			DBMS_OUTPUT.PUT_LINE('ID Proveedor: ' || REG_PROV.ID_PROVEEDOR);
			DBMS_OUTPUT.PUT_LINE('Nombre: ' ||REG_PROV.NOMBRE_PROVEEDOR);
			DBMS_OUTPUT.PUT_LINE('Id Articulo: ' || REG_PROV.ID_ARTICULO);
			DBMS_OUTPUT.PUT_LINE('Articulo: 'REG_PROV.NOMBRE_ARTICULO
		END LOOP;
	ELSE
		FOR REG_PROV IN ( SELECT 
							P.ID_PROVEEDOR,
							P.NOMBRE_PROVEEDOR,
							A.ID_ARTICULO,
							A.NOMBRE_ARTICULO
							FROM PROVEEDORES2 P, 
							TABLE(V.ARTICULOS_PROVEIDOS) A
							WHERE P.NOMBRE LIKE NOMBRE_PARAM) LOOP
			DBMS_OUTPUT.PUT_LINE('ID Proveedor: ' || REG_PROV.ID_PROVEEDOR);
			DBMS_OUTPUT.PUT_LINE('Nombre: ' ||REG_PROV.NOMBRE_PROVEEDOR);
			DBMS_OUTPUT.PUT_LINE('Id Articulo: ' || REG_PROV.ID_ARTICULO);
			DBMS_OUTPUT.PUT_LINE('Articulo: 'REG_PROV.NOMBRE_ARTICULO
		END LOOP;


	END IF;


END;