/*
	Ejercicio 2

	Inserte el nuevo empleado con los siguientes datos: (Ver en PDF)
*/

INSERT INTO B_EMPLEADOS(
	CEDULA, NOMBRE, APELLIDO, FECHA_ING, FECHA_NACIM,
	CEDULA_JEFE, TELEFONO, DIRECCION, BARRIO
)
SELECT 
	123568, 'Marcio', 'Balmaceda', SYSDATE, '04/02/1970',(
		SELECT CEDULA 
	 	FROM B_EMPLEADOS
	 	WHERE NOMBRE LIKE 'José' 
	 	AND APELLIDO LIKE 'Caniza' 
	) CEDULA_JEFE, 
	E.TELEFONO,
	E.DIRECCION,
	E.BARRIO
FROM (
	SELECT TELEFONO, DIRECCION, BARRIO 
	FROM B_EMPLEADOS
	WHERE NOMBRE LIKE 'Jose' 
	AND APELLIDO LIKE 'Balmaceda' 
) E;

