/*
	Ejercicio 2

	Basado en la consulta anterior (Ejercicio 1), determine la mayor y menor asignación en cada área. Su consulta tendrá: Nombre de área, Asignación Máxima, Asignación Mínima.
*/

SELECT 
	A.NOMBRE_AREA
	TO_CHAR(MAX(S.ASIGNACION),'9G999G999G999') ASIGNACION_MAX, 
	TO_CHAR(MIN(S.ASIGNACION),'9G999G999G999') ASIGNACION_MIN
FROM B_POSICION_ACTUAL P
INNER JOIN B_EMPLEADOS E
ON E.CEDULA = P.CEDULA
INNER JOIN B_CATEGORIAS_SALARIALES S
ON S.COD_CATEGORIA = P.COD_CATEGORIA
INNER JOIN B_AREAS A
ON A.ID = P.ID_AREA
WHERE S.FECHA_FIN IS NULL
AND P.FECHA_FIN IS NULL
GROUP BY A.ID;
