/*
	Ejercicio 3

	Determine el nombre y apellido, nombre de categoría, asignación y área del empleado (o empleados) que tienen la máxima asignación vigente. Pruebe con un subquery normal, y luego con la cláusula WITH:
*/


--Utilizando subquery
SELECT 
	E.NOMBRE || ' ' || E.APELLIDO NOMBRE_APELLIDO,
	S.NOM_CAT NOMBRE_CATEGORIA,
	S.ASIGNACION,
	A.NOMBRE_AREA
FROM B_POSICION_ACTUAL P
INNER JOIN B_EMPLEADOS E
ON E.CEDULA = P.CEDULA
INNER JOIN B_CATEGORIAS_SALARIALES S
ON S.COD_CATEGORIA = P.COD_CATEGORIA
INNER JOIN B_AREAS A
ON A.ID = P.ID_AREA
WHERE S.FECHA_FIN IS NULL
AND P.FECHA_FIN IS NULL
AND B.ASIGNACION = (
	SELECT MAX(ASIGNACION) ASIGNACION 
	FROM B_CATEGORIAS_SALARIALES 
)
GROUP BY E.CEDULA;


-- Utilizando WITH

WITH TMP_EMPLEADOS AS(
	SELECT 
		E.NOMBRE || ' ' || E.APELLIDO NOMBRE_APELLIDO,
		S.NOM_CAT NOMBRE_CATEGORIA,
		S.ASIGNACION,
		A.NOMBRE_AREA
	FROM B_POSICION_ACTUAL P
	INNER JOIN B_EMPLEADOS E
	ON E.CEDULA = P.CEDULA
	INNER JOIN B_CATEGORIAS_SALARIALES S
	ON S.COD_CATEGORIA = P.COD_CATEGORIA
	INNER JOIN B_AREAS A
	ON A.ID = P.ID_AREA
	WHERE S.FECHA_FIN IS NULL
	AND P.FECHA_FIN IS NULL
	GROUP BY E.CEDULA
)

SELECT 
	MA.NOMBRE_APELLIDO,
	MA.NOMBRE_CATEGORIA,
	MA.ASIGNACION,
	MA.NOMBRE_AREA
FROM TMP_EMPLEADOS MA
WHERE MA.ASIGNACION = ( 
	SELECT 
	MAX(TMP_EMPLEADOS.ASIGNACION) MAX_ASIG  
	FROM TMP_EMPLEADOS TE 
);

