
-- Ejercicio 5
CREATE OR REPLACE TRIGGER T_VERIFICAR_RESERVA 
BEFORE INSERT ON RESERVA_TRAMO
DECLARE
	V_CANT_DISPONIBLES 	NUMBER;
BEGIN

	V_CANT_DISPONIBLES := PKG_VUELO.F_DETERMINAR_DISPONIBILIDAD(
		:new.ID_ESCALA, 
		:new.FECHA_SALIDA_PROGRAMADA, 
		:new.CLASE
	);

	-- Si no hay asientos disponibles
	IF V_CANT_DISPONIBLES == 0 THEN
		DBMS_OUT.PUT_LINE('No hay asientos disponibles');
	END IF;
END;